-- migrate:up
ALTER TABLE users ADD COLUMN memory INTEGER DEFAULT 65535 NOT NULL;
ALTER TABLE users ADD COLUMN threads INTEGER DEFAULT 1 NOT NULL;

-- migrate:down
ALTER TABLE users DROP COLUMN IF EXISTS memory;
ALTER TABLE users DROP COLUMN IF EXISTS threads;
